# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Initiating Terrascan"
    docker run -v "$(pwd):/src" accurics/terrascan -l /src
    echo "Scan Executed Successfully"
  displayName: 'Terrascan'

- script: |
    echo "Initiating Checkov Scan"
    docker run -v "$(pwd):/src" bridgecrew/checkov -d /src
    echo "Scan Executed Successfully"
  displayName: 'Checkov Scan'
  
- script: |
    echo "Initiating tfsec Scan"
    docker run --rm -v "$(pwd):/src" liamg/tfsec /src
    echo "Scan Executed Successfully"
  displayName: 'tfsec Scan'
