# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: hook
  value: https://hooks.slack.com/services/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 
- name: user
  value: azure-pipeline
- name: channel
  value: infrastucture-code-scanning

steps:
- script: |
    echo "Initiating Terrascan"
    docker run -v "$(pwd):/src" accurics/terrascan -l /src | bash slack_message.sh -h ${{ variables.hook }} -c ${{ variables.channel }} -u ${{ variables.user }} -i comet -C 1974D2
    echo "Scan Executed Successfully"
  displayName: 'Terrascan'

- script: |
    echo "Initiating Checkov Scan"
    docker run -v "$(pwd):/src" bridgecrew/checkov -d /src
    echo "Scan Executed Successfully"
  displayName: 'Checkov Scan'
  
- script: |
    echo "Initiating tfsec Scan"
    docker run --rm -v "$(pwd):/src" liamg/tfsec /src
    echo "Scan Executed Successfully"
  displayName: 'tfsec Scan'
