# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
- script: |
    docker run --rm -v "$(pwd):/src" liamg/tfsec /src
  displayName: 'tfsec scan'


- script: |
    pip3 install -Iv terrascan==0.2.3
  displayName: 'Terrascan'


- script: |
    pip3 install --upgrade setuptools
    pip3 install checkov
  displayName: 'Checkov Scan'
